blank_issues_enabled: false
contact_links:
  - name: Buggo
    url: https://github.com/jdbruijn/test/issues/new?template=bug.md
    about: bug repo
  - name: Start a discussion
    url: https://github.com/jdbruijn/test/discussions/new
    about: If you have any questions or doubts about whether you should create a feature request or bug report, please click here to create a Discussion instead of an Issue.
